language: node_js
node_js:
- '6.9'
before_script:
- npm install -g @angular/cli
addons:
  ssh_known_hosts: fais-mes-courses.fr
  apt:
    packages:
    - sshpass
script:
- ng build --prod
notifications:
  email:
    on_failure: change
    on_success: change
before_install:
- openssl aes-256-cbc -K $encrypted_5ead5ffb0e73_key -iv $encrypted_5ead5ffb0e73_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: master
